# Generated by Django 6.0 on 2026-03-11 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0021_receivedbundle_so'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchForFirstWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('shade', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('SAP', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstWashBundleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_for_first_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bundles', to='wet_process.batchforfirstwash')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.receivedbundle')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFirstWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_start', models.DateTimeField(auto_now_add=True)),
                ('loading_started_by', models.CharField(max_length=100)),
                ('loading_finish', models.DateTimeField(blank=True, null=True)),
                ('loading_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('process_finish', models.DateTimeField(blank=True, null=True)),
                ('process_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('unload_finish', models.DateTimeField(blank=True, null=True)),
                ('unload_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_for_first_wash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_wash_process', to='wet_process.batchforfirstwash')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_wash_processes', to='wet_process.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFirstWashHydro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydro_in', models.DateTimeField(auto_now_add=True)),
                ('hydro_in_by', models.CharField(max_length=100)),
                ('hydro_out', models.DateTimeField(blank=True, null=True)),
                ('hydro_out_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_for_first_wash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_first_wash_hydro', to='wet_process.batchforfirstwash')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_wash_hydro_processes', to='wet_process.machine')),
            ],
        ),
        migrations.CreateModel(
            name='FirstWashBatchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpo', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('so', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('batch_for_first_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_batches', to='wet_process.batchforfirstwash')),
            ],
            options={
                'unique_together': {('batch_for_first_wash', 'mpo')},
            },
        ),
        migrations.CreateModel(
            name='ProcessFirstWashDryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conveyor', 'Conveyor'), ('oven', 'Oven'), ('tumble', 'Tumble')], max_length=10)),
                ('dryer_in', models.DateTimeField(auto_now_add=True)),
                ('dryer_in_by', models.CharField(max_length=100)),
                ('dryer_out', models.DateTimeField(blank=True, null=True)),
                ('dryer_out_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_for_first_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_wash_dryer_processes', to='wet_process.batchforfirstwash')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_wash_dryer_processes', to='wet_process.machine')),
            ],
            options={
                'unique_together': {('batch_for_first_wash', 'type')},
            },
        ),
    ]
