# Generated by Django 6.0 on 2026-03-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstwashbundlesource',
            old_name='bundle',
            new_name='received',
        ),
    ]
