# Generated by Django 6.0 on 2026-04-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_barcode', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(max_length=100)),
                ('rejected_at', models.DateTimeField(auto_now=True)),
                ('rejected_by', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='wet_process.batch')),
            ],
        ),
    ]
