# Generated by Django 6.0 on 2026-02-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_receivedbundle_buyer_receivedbundle_style'),
        ('wet_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstWashBatchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.batch')),
                ('first_wash_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_batches', to='wet_process.batchforfirstwash')),
            ],
        ),
        migrations.CreateModel(
            name='FirstWashBundleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.IntegerField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.receivedbundle')),
                ('first_wash_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bundles', to='wet_process.batchforfirstwash')),
            ],
        ),
    ]
