# Generated by Django 6.0 on 2026-03-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wet_process', '0002_rename_bundle_firstwashbundlesource_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchforfirstwash',
            name='status',
        ),
        migrations.CreateModel(
            name='WashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('rejections', models.PositiveIntegerField(default=0)),
                ('rewash_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_rewash_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
