# Generated by Django 6.0 on 2026-02-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0002_firstwashbatchsource_firstwashbundlesource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstwashbatchsource',
            old_name='first_wash_batch',
            new_name='batch_for_first_wash',
        ),
        migrations.RenameField(
            model_name='firstwashbundlesource',
            old_name='first_wash_batch',
            new_name='batch_for_first_wash',
        ),
    ]
