# Generated by Django 6.0 on 2026-03-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0003_remove_batchforfirstwash_status_washlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washlog',
            name='total_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
