# Generated by Django 6.0 on 2026-02-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0003_rename_first_wash_batch_firstwashbatchsource_batch_for_first_wash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstwashbatchsource',
            old_name='quantity_taken',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='firstwashbundlesource',
            old_name='quantity_taken',
            new_name='quantity',
        ),
    ]
