# Generated by Django 6.0 on 2026-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0003_processfirstwash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processfirstwash',
            name='standard_time',
            field=models.DurationField(),
        ),
    ]
