# Generated by Django 6.0 on 2026-04-07 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0004_alter_processfirstwash_standard_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFirstWashHydro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_time', models.DurationField()),
                ('hydro_in', models.DateTimeField(auto_now_add=True)),
                ('hydro_in_by', models.CharField(max_length=100)),
                ('hydro_out', models.DateTimeField(blank=True, null=True)),
                ('hydro_out_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_first_wash_hydro', to='wet_process.batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wet_process.machine')),
            ],
        ),
    ]
