# Generated by Django 6.0 on 2026-03-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wet_process', '0004_alter_washlog_total_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_barcode', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('rejected_at', models.DateTimeField(auto_now=True)),
                ('rejected_by', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
    ]
