# Generated by Django 6.0 on 2026-03-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0005_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFirstWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_start', models.DateTimeField(auto_now_add=True)),
                ('loading_started_by', models.CharField(max_length=100)),
                ('loading_finish', models.DateTimeField(blank=True, null=True)),
                ('loading_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('process_finish', models.DateTimeField(blank=True, null=True)),
                ('process_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('unload_finish', models.DateTimeField(blank=True, null=True)),
                ('unload_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_wash_process', to='wet_process.batchforfirstwash')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_wash_processes', to='wet_process.machine')),
            ],
        ),
    ]
