# Generated by Django 6.0 on 2026-03-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wet_process', '0006_batchforrewash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewashBatchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('batch_for_rewash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_batches', to='wet_process.batchforrewash')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
    ]
