# Generated by Django 6.0 on 2026-03-14 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wet_process', '0007_rewashbatchsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstwashbatchsource',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rewashbatchsource',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='rewashbatchsource',
            unique_together={('batch_for_rewash', 'content_type', 'object_id')},
        ),
    ]
