# Generated by Django 6.0 on 2026-03-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0007_processfirstwashhydro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFirstWashDryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conveyor', 'Conveyor'), ('oven', 'Oven'), ('tumble', 'Tumble')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.CharField(max_length=100)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_wash_dryer_processes', to='wet_process.batchforfirstwash')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_wash_dryer_processes', to='wet_process.machine')),
            ],
            options={
                'unique_together': {('batch', 'type')},
            },
        ),
    ]
