# Generated by Django 6.0 on 2026-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0007_rename_created_by_batch_operator_batch_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchsource',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='batchsource',
            name='object_id',
        ),
        migrations.AddField(
            model_name='batchsource',
            name='mpo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchsource',
            name='rejection_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchsource',
            name='so',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchsource',
            name='style',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
