# Generated by Django 6.0 on 2026-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0008_remove_batchsource_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchsource',
            name='mpo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='batchsource',
            name='so',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='batchsource',
            name='style',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
    ]
