# Generated by Django 6.0 on 2026-03-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0008_processfirstwashdryer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processfirstwash',
            old_name='batch',
            new_name='batch_for_first_wash',
        ),
        migrations.RenameField(
            model_name='processfirstwashdryer',
            old_name='batch',
            new_name='batch_for_first_wash',
        ),
        migrations.RenameField(
            model_name='processfirstwashhydro',
            old_name='batch',
            new_name='batch_for_first_wash',
        ),
        migrations.AlterUniqueTogether(
            name='processfirstwashdryer',
            unique_together={('batch_for_first_wash', 'type')},
        ),
    ]
