# Generated by Django 6.0 on 2026-03-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0009_rename_batch_processfirstwash_batch_for_first_wash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processfirstwashdryer',
            old_name='started_at',
            new_name='dryer_in',
        ),
        migrations.RenameField(
            model_name='processfirstwashdryer',
            old_name='started_by',
            new_name='dryer_in_by',
        ),
        migrations.RenameField(
            model_name='processfirstwashdryer',
            old_name='ended_at',
            new_name='dryer_out',
        ),
        migrations.RenameField(
            model_name='processfirstwashdryer',
            old_name='ended_by',
            new_name='dryer_out_by',
        ),
    ]
