# Generated by Django 6.0 on 2026-05-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_garmentunit_id_and_more'),
        ('wet_process', '0009_alter_batchsource_mpo_alter_batchsource_so_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSourcePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='wet_process.batchsource')),
                ('garment_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.garmentunit')),
            ],
        ),
    ]
