# Generated by Django 6.0 on 2026-05-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0010_batchsourcepiece'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalBatch',
        ),
    ]
