# Generated by Django 6.0 on 2026-05-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0011_delete_internalbatch'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchsource',
            constraint=models.UniqueConstraint(fields=('batch', 'mpo'), name='unique_batch_mpo'),
        ),
    ]
