# Generated by Django 6.0 on 2026-05-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_garmentunit_id_and_more'),
        ('wet_process', '0012_batchsource_unique_batch_mpo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchsourcepiece',
            constraint=models.UniqueConstraint(fields=('batch_source', 'garment_unit'), name='unique_batch_source_garment_unit'),
        ),
    ]
