# Generated by Django 6.0 on 2026-05-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wet_process", "0013_batchsourcepiece_unique_batch_source_garment_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("first_wash", "First Wash"),
                            ("second_wash", "Second Wash"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("normal_wash", "Normal Wash"), ("rewash", "Rewash")],
                        max_length=20,
                    ),
                ),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "stage", "type"), name="unique_year_stage_type"
                    )
                ],
            },
        ),
    ]
