# Generated by Django 6.0 on 2026-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0014_batchsequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchsequence',
            old_name='last_sequence',
            new_name='last_number',
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.CharField(choices=[('first_wash', 'First Wash'), ('second_wash', 'Second Wash'), ('third_wash', 'Third Wash'), ('final_wash', 'Final Wash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='batchsequence',
            name='stage',
            field=models.CharField(choices=[('first_wash', 'First Wash'), ('second_wash', 'Second Wash'), ('third_wash', 'Third Wash'), ('final_wash', 'Final Wash')], max_length=20),
        ),
    ]
