# Generated by Django 6.0 on 2026-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_garmentunit_id_and_more'),
        ('wet_process', '0015_rename_last_sequence_batchsequence_last_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batchsourcepiece',
            name='unique_batch_source_garment_unit',
        ),
        migrations.AddConstraint(
            model_name='batchsourcepiece',
            constraint=models.UniqueConstraint(fields=('garment_unit',), name='unique_garment_unit'),
        ),
    ]
