# Generated by Django 6.0 on 2026-05-24 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_garmentunit_status'),
        ('wet_process', '0016_remove_batchsourcepiece_unique_batch_source_garment_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejection',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='rejection',
            name='individual_barcode',
        ),
        migrations.RemoveField(
            model_name='rejection',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='rejection',
            name='rejected_by',
        ),
        migrations.AddField(
            model_name='rejection',
            name='batch_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='wet_process.batchsource'),
        ),
        migrations.AddField(
            model_name='rejection',
            name='garment_unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.garmentunit'),
        ),
        migrations.AddField(
            model_name='rejection',
            name='operator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rejection',
            name='rejection_reason',
            field=models.CharField(choices=[('stain', 'Stain'), ('color_bleed', 'Color Bleed'), ('fabric_damage', 'Fabric Damage'), ('shrinkage', 'Shrinkage'), ('stitch_damage', 'Stitch Damage'), ('button_missing', 'Button Missing'), ('zipper_damage', 'Zipper Damage'), ('wrinkle', 'Wrinkle'), ('odor', 'Odor'), ('improper_wash', 'Improper Wash'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ready_to_wash', 'Ready To Wash'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='ready_to_wash', max_length=20),
        ),
    ]
