# Generated by Django 6.0 on 2026-05-24 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_garmentunit_status'),
        ('wet_process', '0017_remove_rejection_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejection',
            name='batch_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='wet_process.batchsource'),
        ),
        migrations.AlterField(
            model_name='rejection',
            name='garment_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.garmentunit'),
        ),
        migrations.AlterField(
            model_name='rejection',
            name='operator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejection',
            name='rejection_reason',
            field=models.CharField(choices=[('stain', 'Stain'), ('color_bleed', 'Color Bleed'), ('fabric_damage', 'Fabric Damage'), ('shrinkage', 'Shrinkage'), ('stitch_damage', 'Stitch Damage'), ('button_missing', 'Button Missing'), ('zipper_damage', 'Zipper Damage'), ('wrinkle', 'Wrinkle'), ('odor', 'Odor'), ('improper_wash', 'Improper Wash'), ('other', 'Other')], max_length=100),
        ),
    ]
