# Generated by Django 6.0 on 2026-06-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0018_alter_rejection_batch_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSecondWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_time', models.DurationField()),
                ('loading_start', models.DateTimeField(auto_now_add=True)),
                ('loading_started_by', models.CharField(max_length=100)),
                ('loading_finish', models.DateTimeField(blank=True, null=True)),
                ('loading_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('process_finish', models.DateTimeField(blank=True, null=True)),
                ('process_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('unload_finish', models.DateTimeField(blank=True, null=True)),
                ('unload_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_second_wash', to='wet_process.batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wet_process.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSecondWashHydro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_time', models.DurationField()),
                ('hydro_in', models.DateTimeField(auto_now_add=True)),
                ('hydro_in_by', models.CharField(max_length=100)),
                ('hydro_out', models.DateTimeField(blank=True, null=True)),
                ('hydro_out_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_second_wash_hydro', to='wet_process.batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wet_process.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSecondWashDryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_time', models.DurationField()),
                ('type', models.CharField(choices=[('conveyor', 'Conveyor'), ('oven', 'Oven'), ('tumble', 'Tumble')], max_length=10)),
                ('dryer_in', models.DateTimeField(auto_now_add=True)),
                ('dryer_in_by', models.CharField(max_length=100)),
                ('dryer_out', models.DateTimeField(blank=True, null=True)),
                ('dryer_out_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_wash_dryer_processes', to='wet_process.batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_wash_dryer_processes', to='wet_process.machine')),
            ],
            options={
                'unique_together': {('batch', 'type')},
            },
        ),
    ]
