# Generated by Django 6.0 on 2026-06-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0019_processsecondwash_processsecondwashhydro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
