# Generated by Django 6.0 on 2026-06-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0020_machine_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydroProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_time', models.DurationField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.CharField(max_length=100)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hydro_process', to='wet_process.batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wet_process.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WashProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_time', models.DurationField()),
                ('loading_start', models.DateTimeField(auto_now_add=True)),
                ('loading_started_by', models.CharField(max_length=100)),
                ('loading_finish', models.DateTimeField(blank=True, null=True)),
                ('loading_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('process_finish', models.DateTimeField(blank=True, null=True)),
                ('process_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('unloading_finish', models.DateTimeField(blank=True, null=True)),
                ('unloading_finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wash_process', to='wet_process.batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wet_process.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DryerProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_time', models.DurationField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.CharField(max_length=100)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('finished_by', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('conveyor', 'Conveyor'), ('oven', 'Oven'), ('tumble', 'Tumble')], max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dryer_processes', to='wet_process.batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wet_process.machine')),
            ],
            options={
                'unique_together': {('batch', 'type')},
            },
        ),
    ]
