# Generated by Django 6.0 on 2026-06-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0021_hydroprocess_washprocess_dryerprocess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processfirstwashdryer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='processfirstwashdryer',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='processfirstwashdryer',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='processfirstwashhydro',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='processfirstwashhydro',
            name='machine',
        ),
        migrations.DeleteModel(
            name='ProcessFirstWash',
        ),
        migrations.DeleteModel(
            name='ProcessFirstWashDryer',
        ),
        migrations.DeleteModel(
            name='ProcessFirstWashHydro',
        ),
    ]
