# Generated by Django 6.0 on 2026-06-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0022_alter_processfirstwashdryer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processsecondwashdryer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='processsecondwashdryer',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='processsecondwashdryer',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='processsecondwashhydro',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='processsecondwashhydro',
            name='machine',
        ),
        migrations.DeleteModel(
            name='ProcessSecondWash',
        ),
        migrations.DeleteModel(
            name='ProcessSecondWashDryer',
        ),
        migrations.DeleteModel(
            name='ProcessSecondWashHydro',
        ),
    ]
