# Generated by Django 6.0.6 on 2026-06-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0023_alter_processsecondwashdryer_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejection',
            name='batch_source',
        ),
        migrations.AddField(
            model_name='rejection',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='wet_process.batch'),
        ),
    ]
