# Generated by Django 6.0.6 on 2026-06-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0024_remove_rejection_batch_source_rejection_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejection',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='wet_process.batch'),
        ),
    ]
