# Generated by Django 6.0.6 on 2026-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0025_alter_rejection_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsource',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
