# Generated by Django 6.0.6 on 2026-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0026_batchsource_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
