# Generated by Django 6.0.6 on 2026-06-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wet_process', '0027_batch_total_received_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSourceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('receive', 'Receive'), ('rewash', 'Rewash'), ('rejection', 'Rejection')], max_length=20)),
                ('previous_quantity', models.PositiveIntegerField()),
                ('incoming_quantity', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=100)),
                ('batch_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='wet_process.batchsource')),
            ],
        ),
    ]
