# Generated by Django 6.0 on 2026-04-16 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('buyer', 'style', 'color')},
            },
        ),
        migrations.CreateModel(
            name='PlanningRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stage', models.CharField(max_length=100)),
                ('master_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='common.masterplan')),
            ],
            options={
                'unique_together': {('master_plan', 'sequence')},
            },
        ),
    ]
