# Generated by Django 6.0 on 2026-04-20 03:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WetProcessRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stage', models.CharField(max_length=100)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wet_process_route_steps', to='common.planningroutestep')),
            ],
            options={
                'unique_together': {('planning', 'sequence')},
            },
        ),
    ]
