# Generated by Django 6.0 on 2026-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_wetprocessroutestep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningroutestep',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='wetprocessroutestep',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='masterplan',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='planningroutestep',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wetprocessroutestep',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='masterplan',
            constraint=models.UniqueConstraint(fields=('buyer', 'style', 'color'), name='unique_master_plan'),
        ),
        migrations.AddConstraint(
            model_name='planningroutestep',
            constraint=models.UniqueConstraint(fields=('master_plan', 'sequence'), name='unique_planning_sequence'),
        ),
        migrations.AddConstraint(
            model_name='wetprocessroutestep',
            constraint=models.UniqueConstraint(fields=('planning', 'sequence'), name='unique_wet_process_sequence'),
        ),
    ]
