# Generated by Django 6.0 on 2026-04-20 04:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_wetprocessstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stage', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='wetprocessstep',
            name='unique_wet_process_sequence',
        ),
        migrations.AddField(
            model_name='subroutestep',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_steps', to='common.routestep'),
        ),
        migrations.RemoveField(
            model_name='wetprocessstep',
            name='planning',
        ),
        migrations.AddConstraint(
            model_name='subroutestep',
            constraint=models.UniqueConstraint(fields=('planning', 'sequence'), name='unique_wet_process_sequence'),
        ),
        migrations.DeleteModel(
            name='WetProcessStep',
        ),
    ]
