# Generated by Django 6.0 on 2026-04-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_subroutestep_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routestep',
            name='unique_planning_sequence',
        ),
        migrations.RemoveConstraint(
            model_name='subroutestep',
            name='unique_wet_process_sequence',
        ),
        migrations.AddConstraint(
            model_name='routestep',
            constraint=models.UniqueConstraint(fields=('master_plan', 'sequence'), name='unique_route_sequence'),
        ),
        migrations.AddConstraint(
            model_name='subroutestep',
            constraint=models.UniqueConstraint(fields=('planning', 'sequence'), name='unique_sub_route_sequence'),
        ),
    ]
