# Generated by Django 6.0 on 2026-04-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_routestep_unique_planning_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subroutestep',
            name='unique_sub_route_sequence',
        ),
        migrations.RenameField(
            model_name='subroutestep',
            old_name='planning',
            new_name='route_step',
        ),
        migrations.AddConstraint(
            model_name='subroutestep',
            constraint=models.UniqueConstraint(fields=('route_step', 'sequence'), name='unique_sub_route_sequence'),
        ),
    ]
