# Generated by Django 6.0 on 2026-05-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_subroutestep_unique_sub_route_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_barcode', models.CharField(max_length=100, unique=True)),
                ('so', models.CharField(max_length=100)),
                ('mpo', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('marker', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('shade', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('rejected', 'Rejected'), ('whisker_in', 'Whisker In'), ('whisker_out', 'Whisker Out'), ('brush_in', 'Brush In'), ('brush_out', 'Brush Out')], default='received', max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
