# Generated by Django 6.0 on 2026-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_garmentunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmentunit',
            name='id',
        ),
        migrations.AlterField(
            model_name='garmentunit',
            name='individual_barcode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
