# Generated by Django 6.0 on 2026-05-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_garmentunit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentunit',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('rejected', 'Rejected'), ('whisker_in', 'Whisker In'), ('whisker_out', 'Whisker Out'), ('brush_in', 'Brush In'), ('brush_out', 'Brush Out'), ('dry_complete', 'Dry Complete')], default='received', max_length=100),
        ),
    ]
