# Generated by Django 6.0 on 2026-01-04 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpo', models.CharField(max_length=100, unique=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stage', models.CharField(max_length=100)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='production.planning')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('planning', 'sequence'), ('planning', 'stage')},
            },
        ),
    ]
