# Generated by Django 6.0 on 2026-01-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpo', models.CharField(max_length=100)),
                ('bundle_no', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=50)),
                ('shade', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('allocated', 'Allocated')], default='received', max_length=20)),
            ],
            options={
                'unique_together': {('mpo', 'bundle_no')},
            },
        ),
    ]
