# Generated by Django 6.0 on 2026-01-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_receivedbundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedbundle',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
