# Generated by Django 6.0 on 2026-01-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_bundles', to='production.batch')),
                ('received', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_bundle', to='production.receivedbundle')),
            ],
            options={
                'unique_together': {('batch', 'received')},
            },
        ),
    ]
