# Generated by Django 6.0 on 2026-01-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_batchbundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchbundle',
            name='added_by',
        ),
    ]
