# Generated by Django 6.0 on 2026-01-07 04:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_batchbundle_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStage',
            fields=[
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stage', serialize=False, to='production.batch')),
                ('current_stage', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_status', models.CharField(choices=[('in', 'In'), ('closed', 'Closed')], max_length=10)),
            ],
        ),
    ]
