# Generated by Django 6.0 on 2026-01-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_batchstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('entered_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.CharField(max_length=100)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='production.batch')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
    ]
