# Generated by Django 6.0 on 2026-01-07 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_batchstagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstagehistory',
            name='sequence',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
