# Generated by Django 6.0 on 2026-01-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_batchstagehistory_sequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchstagehistory',
            unique_together={('batch', 'sequence'), ('batch', 'stage')},
        ),
    ]
