# Generated by Django 6.0 on 2026-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_batchstagehistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstage',
            name='production_status',
            field=models.CharField(choices=[('in', 'In'), ('closed', 'Closed')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
