# Generated by Django 6.0 on 2026-01-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_batchstage_production_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200, unique=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
