# Generated by Django 6.0 on 2026-01-18 05:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_stagename'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchQcStageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('rejection_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_stage_summaries', to='production.batch')),
            ],
            options={
                'unique_together': {('batch', 'stage')},
            },
        ),
    ]
