# Generated by Django 6.0 on 2026-01-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_batchqcstagesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_id', models.CharField(max_length=100, unique=True)),
                ('stage', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('stitching_defect', 'Stitching defect'), ('fabric_defect', 'Fabric defect'), ('measurement_issue', 'Measurement issue'), ('color_mismatch', 'Color mismatch'), ('physical_damage', 'Physical damage'), ('finishing_issue', 'Finishing issue'), ('missing_part', 'Missing part'), ('other', 'Other')], max_length=100)),
                ('rejected_at', models.DateTimeField(auto_now=True)),
                ('rejected_by', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='production.batch')),
            ],
        ),
    ]
