# Generated by Django 6.0 on 2026-01-20 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_rejection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receivedbundle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='receivedbundle',
            name='bundle_barcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedbundle',
            name='marker',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='receivedbundle',
            unique_together={('mpo', 'marker')},
        ),
    ]
