# Generated by Django 6.0 on 2026-01-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_alter_receivedbundle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedbundle',
            name='bundle_barcode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
