# Generated by Django 6.0 on 2026-01-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_receivedbundle_bundle_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receivedbundle',
            unique_together={('mpo', 'marker', 'bundle_no')},
        ),
    ]
