# Generated by Django 6.0 on 2026-01-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_receivedbundle_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejection',
            old_name='individual_id',
            new_name='individual_barcode',
        ),
    ]
