# Generated by Django 6.0 on 2026-01-28 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_rename_individual_id_rejection_individual_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedbundle',
            name='buyer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedbundle',
            name='style',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
