# Generated by Django 6.0 on 2026-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_receivedbundle_buyer_receivedbundle_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchstage',
            name='production_status',
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('in', 'In'), ('closed', 'Closed')], default='in', max_length=10),
        ),
    ]
