# Generated by Django 6.0 on 2026-02-24 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_remove_batchstage_production_status_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedbundle',
            name='so',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
