# Generated by Django 6.0 on 2026-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_receivedbundle_so'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningroutestep',
            name='stage',
            field=models.CharField(choices=[('whisker', 'Whisker'), ('laser_whisker', 'Laser Whisker'), ('brush', 'Brush'), ('laser_brush', 'Laser Brush'), ('wrinkle', 'Wrinkle'), ('tag', 'Tag'), ('tie', 'Tie')], max_length=100),
        ),
    ]
