# Generated by Django 6.0 on 2026-05-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0009_remove_garmentunit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('whisker', 'Whisker'), ('laser_whisker', 'Laser Whisker'), ('brush', 'Brush'), ('laser_brush', 'Laser Brush'), ('wrinkle', 'Wrinkle'), ('tag', 'Tag'), ('tie', 'Tie')], max_length=100)),
                ('action', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('rejected', 'Rejected')], max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('garment_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='common.garmentunit')),
            ],
        ),
    ]
