# Generated by Django 6.0 on 2026-05-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_garmentunit_id_and_more'),
        ('dry_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackinghistory',
            options={'ordering': ['scanned_at']},
        ),
        migrations.AddConstraint(
            model_name='trackinghistory',
            constraint=models.UniqueConstraint(fields=('garment_unit', 'stage', 'action'), name='unique_garment_unit_stage_action'),
        ),
    ]
