# Generated by Django 6.0 on 2026-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dry_process', '0002_alter_trackinghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
