# Generated by Django 6.0 on 2026-06-17 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dry_process', '0003_trackinghistory_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mpo', 'color'), name='unique_mpo_color')],
            },
        ),
        migrations.CreateModel(
            name='PlanningRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stage', models.CharField(choices=[('whisker', 'Whisker'), ('laser_whisker', 'Laser Whisker'), ('brush', 'Brush'), ('laser_brush', 'Laser Brush'), ('wrinkle', 'Wrinkle'), ('tag', 'Tag'), ('tie', 'Tie')], max_length=100)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='dry_process.planning')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('planning', 'sequence'), ('planning', 'stage')},
            },
        ),
    ]
